//! `Cargo.lock` update strategy after Cargo-ecosystem ReleaseUnit
//! bumps.
//!
//! Phase J of `BELAF_MASTER_PLAN.md`. Three-step strategy:
//!
//! 1. Try `cargo update -p <crate-name> --workspace` (focused, fast)
//! 2. On failure, fall back to `cargo update --workspace` (broader,
//!    slower — recovers from indirect-dep version mismatches)
//! 3. If `cargo metadata` is unavailable in the repo (Bazel-managed
//!    C deps), best-effort with `--offline` flag; failure becomes
//!    a `warn!` log, not a hard error (Bazel's `crate_index`
//!    regenerates the lockfile on build anyway).

use std::path::Path;
use std::process::Command;

use thiserror::Error;
use tracing::warn;

#[derive(Debug, Error)]
pub enum CargoLockError {
    #[error("`cargo update -p {crate_name}` failed: {stderr}")]
    PerCrateFailed { crate_name: String, stderr: String },

    #[error("`cargo update --workspace` fallback failed: {stderr}")]
    WorkspaceFallbackFailed { stderr: String },

    #[error("failed to spawn `cargo update`: {source}")]
    Spawn {
        #[source]
        source: std::io::Error,
    },
}

pub type Result<T> = std::result::Result<T, CargoLockError>;

/// Refresh `Cargo.lock` after one Cargo-ecosystem ReleaseUnit bumped.
/// Per-crate first, workspace-fallback if that fails.
///
/// `cwd` is the directory containing the workspace `Cargo.toml`
/// (typically the repo root). `crate_name` is the bumped crate's
/// `[package].name` (matches `cargo update -p`'s arg shape).
pub fn update_for_crate(crate_name: &str, cwd: &Path) -> Result<()> {
    match run_cargo(&["update", "-p", crate_name, "--workspace"], cwd) {
        Ok(()) => Ok(()),
        Err(per_crate_err) => {
            warn!(
                "cargo update -p {} failed, falling back to --workspace: {}",
                crate_name, per_crate_err
            );
            match run_cargo(&["update", "--workspace"], cwd) {
                Ok(()) => Ok(()),
                Err(_workspace_err) => {
                    // Bubble up the per-crate error (the user's
                    // primary action) rather than the fallback's,
                    // since the per-crate is what they would
                    // normally invoke.
                    Err(per_crate_err)
                }
            }
        }
    }
}

/// Best-effort `Cargo.lock` update that DOWNGRADES failures to
/// `warn!` logs. Used for Bazel-managed workspaces where the lock
/// file is regenerated by Bazel itself; belaf's update is just a
/// nicety. Never returns Err.
pub fn update_for_crate_best_effort(crate_name: &str, cwd: &Path) {
    match run_cargo(&["update", "-p", crate_name, "--offline"], cwd) {
        Ok(()) => {}
        Err(e) => {
            warn!(
                "best-effort cargo update for `{}` failed (treat as Bazel-managed lockfile): {}",
                crate_name, e
            );
        }
    }
}

fn run_cargo(args: &[&str], cwd: &Path) -> Result<()> {
    let output = Command::new("cargo")
        .args(args)
        .current_dir(cwd)
        .output()
        .map_err(|e| CargoLockError::Spawn { source: e })?;

    if output.status.success() {
        return Ok(());
    }

    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
    let crate_name = args.iter().skip_while(|a| **a != "-p").nth(1);
    if let Some(name) = crate_name {
        Err(CargoLockError::PerCrateFailed {
            crate_name: name.to_string(),
            stderr,
        })
    } else {
        Err(CargoLockError::WorkspaceFallbackFailed { stderr })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Build a tiny single-crate cargo project so `cargo update`
    /// has something to operate on.
    fn make_temp_crate(name: &str, version: &str) -> TempDir {
        let dir = TempDir::new().unwrap();
        let cargo_toml =
            format!("[package]\nname = \"{name}\"\nversion = \"{version}\"\nedition = \"2021\"\n");
        std::fs::write(dir.path().join("Cargo.toml"), cargo_toml).unwrap();
        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::write(dir.path().join("src/lib.rs"), "pub fn x() {}\n").unwrap();
        // Generate Cargo.lock by running cargo generate-lockfile (best
        // effort — if cargo isn't available the test will skip).
        let _ = Command::new("cargo")
            .args(["generate-lockfile"])
            .current_dir(dir.path())
            .output();
        dir
    }

    #[test]
    fn update_for_crate_succeeds_on_simple_project() {
        let dir = make_temp_crate("belaf-test-crate", "0.1.0");
        // First check Cargo.lock got generated; if not, cargo isn't
        // available in this test env.
        if !dir.path().join("Cargo.lock").exists() {
            eprintln!("cargo unavailable in test env, skipping");
            return;
        }
        update_for_crate("belaf-test-crate", dir.path()).expect("must succeed");
    }

    #[test]
    fn update_for_crate_unknown_crate_falls_back_to_workspace() {
        // The fallback ALSO succeeds (unknown -p arg becomes a no-op
        // workspace update once the workspace Cargo.lock exists).
        let dir = make_temp_crate("belaf-test-crate", "0.1.0");
        if !dir.path().join("Cargo.lock").exists() {
            eprintln!("cargo unavailable in test env, skipping");
            return;
        }
        // The fallback path is exercised via run_cargo's per-crate
        // failure → workspace retry. The workspace cargo update
        // should succeed regardless of the unknown package name.
        let _ = update_for_crate("definitely-not-a-real-crate-xyz", dir.path());
    }

    #[test]
    fn best_effort_never_returns_err() {
        let dir = TempDir::new().unwrap();
        // No Cargo.toml → cargo update fails → best-effort logs a
        // warn but returns ().
        update_for_crate_best_effort("anything", dir.path());
    }
}
