//! Release manifest handling for PR-based releases.
//!
//! The release manifest is a JSON file in `belaf/releases/` that contains
//! metadata about a pending release. It serves as a contract between the
//! CLI (which creates releases) and the GitHub App (which finalizes them).
//!
//! # Schema version `2.0`
//!
//! The wire format is owned by belaf and defined in
//! `schemas/manifest.v2.0.schema.json`. Rust types are generated by
//! `typify` in `build.rs` and live in [`crate::core::wire::codegen`].
//! This module re-exports the ergonomic domain types from
//! [`crate::core::wire::domain`] under the historical names
//! (`ReleaseManifest`, `ProjectRelease`) and provides a back-compat
//! constructor for call sites that still pass plain strings.

use std::fs;
use std::path::Path;

use serde_json::Map;

pub use crate::core::wire::domain::{
    Group, Manifest as ReleaseManifest, ManifestParseError, Release as ProjectRelease,
    ReleaseStatistics,
};
use crate::core::wire::known::{BumpType, Ecosystem};

pub const MANIFEST_DIR: &str = "belaf/releases";

impl ReleaseManifest {
    /// Serialize and write to disk. Creates parent directories as needed.
    pub fn save_to_file(&self, path: &Path) -> Result<(), std::io::Error> {
        let json = self
            .to_json()
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, json)
    }

    /// Filename for on-disk storage. Always `<manifest_id>.json` (UUID v7
    /// is sortable, so `belaf/releases/` lists chronologically).
    pub fn generate_filename(&self) -> String {
        format!("{}.json", self.manifest_id)
    }
}

impl ProjectRelease {
    /// Construct a release with v1-style string arguments. Classifies
    /// `ecosystem` and `bump_type` into the discriminated unions and
    /// generates a default `tag_name` from `prefix` + `new_version`.
    ///
    /// `prefix` is a v1-era input that's not stored in the v2 manifest
    /// (the wire format now requires the producer to set `tag_name`
    /// explicitly). The default generated here matches the v1 behaviour
    /// so existing call sites keep working until B10 introduces
    /// per-ecosystem `tag_format` overrides.
    pub fn new(
        name: String,
        ecosystem: String,
        previous_version: String,
        new_version: String,
        bump_type: String,
        changelog: String,
        prefix: String,
    ) -> Self {
        let prefix_trimmed = prefix.trim_end_matches('/');
        let tag_name = if prefix_trimmed.is_empty() {
            format!("v{new_version}")
        } else {
            format!("{prefix_trimmed}/v{new_version}")
        };
        let previous_tag = if previous_version.is_empty() {
            None
        } else if prefix_trimmed.is_empty() {
            Some(format!("v{previous_version}"))
        } else {
            Some(format!("{prefix_trimmed}/v{previous_version}"))
        };
        let is_prerelease = detect_prerelease(&new_version);

        Self {
            name,
            ecosystem: Ecosystem::classify(&ecosystem),
            group_id: None,
            previous_version,
            new_version,
            bump_type: BumpType::classify(&bump_type),
            tag_name,
            previous_tag,
            compare_url: None,
            is_prerelease,
            changelog,
            contributors: Vec::new(),
            first_time_contributors: Vec::new(),
            statistics: None,
            x: Map::new(),
        }
    }

    pub fn with_group_id(mut self, group_id: impl Into<String>) -> Self {
        self.group_id = Some(group_id.into());
        self
    }

    pub fn with_compare_url<F>(mut self, base_url: &str, tag_exists: F) -> Self
    where
        F: Fn(&str) -> bool,
    {
        if let Some(prev_tag) = &self.previous_tag {
            if tag_exists(prev_tag) {
                self.compare_url = Some(format!(
                    "{}/compare/{}...{}",
                    base_url.trim_end_matches('/'),
                    prev_tag,
                    self.tag_name
                ));
            } else {
                self.previous_tag = None;
            }
        }
        self
    }

    pub fn with_contributors(mut self, contributors: Vec<String>) -> Self {
        self.contributors = contributors;
        self
    }

    pub fn with_first_time_contributors(mut self, contributors: Vec<String>) -> Self {
        self.first_time_contributors = contributors;
        self
    }

    pub fn with_statistics(mut self, statistics: ReleaseStatistics) -> Self {
        self.statistics = Some(statistics);
        self
    }
}

fn detect_prerelease(version: &str) -> bool {
    let prerelease_markers = ["-alpha", "-beta", "-rc", "-dev", "-pre", "-snapshot"];
    let v = version.to_lowercase();
    prerelease_markers.iter().any(|m| v.contains(m))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_new_has_3_0_schema_version() {
        let m = ReleaseManifest::new("main".into(), "test-user".into());
        assert_eq!(m.schema_version, "3.0");
    }

    #[test]
    fn manifest_new_has_rfc3339_timestamp() {
        let m = ReleaseManifest::new("main".into(), "test-user".into());
        assert!(m.created_at.contains('T'));
        assert!(m.created_at.contains('Z') || m.created_at.contains('+'));
    }

    #[test]
    fn project_release_tag_name_without_prefix() {
        let r = ProjectRelease::new(
            "crate".into(),
            "cargo".into(),
            "1.0.0".into(),
            "1.0.1".into(),
            "patch".into(),
            "Changelog".into(),
            String::new(),
        );
        assert_eq!(r.tag_name, "v1.0.1");
    }

    #[test]
    fn project_release_tag_name_with_prefix() {
        let r = ProjectRelease::new(
            "core".into(),
            "cargo".into(),
            "1.0.0".into(),
            "2.0.0".into(),
            "major".into(),
            "Changelog".into(),
            "packages/core".into(),
        );
        assert_eq!(r.tag_name, "packages/core/v2.0.0");
    }

    #[test]
    fn project_release_classifies_ecosystem_and_bump_type() {
        let r = ProjectRelease::new(
            "x".into(),
            "maven".into(),
            "1.0.0".into(),
            "1.1.0".into(),
            "minor".into(),
            String::new(),
            String::new(),
        );
        assert_eq!(r.ecosystem.as_str(), "maven");
        assert_eq!(r.bump_type.as_str(), "minor");
    }

    #[test]
    fn project_release_compare_url_with_existing_tag() {
        let r = ProjectRelease::new(
            "cli".into(),
            "cargo".into(),
            "0.1.0".into(),
            "0.2.0".into(),
            "minor".into(),
            String::new(),
            "apps/cli".into(),
        )
        .with_compare_url("https://github.com/org/repo", |_| true);
        assert_eq!(r.previous_tag, Some("apps/cli/v0.1.0".to_string()));
        assert_eq!(
            r.compare_url,
            Some(
                "https://github.com/org/repo/compare/apps/cli/v0.1.0...apps/cli/v0.2.0".to_string()
            )
        );
    }

    #[test]
    fn project_release_compare_url_with_nonexistent_tag_clears_previous() {
        let r = ProjectRelease::new(
            "cli".into(),
            "cargo".into(),
            "0.1.0".into(),
            "0.2.0".into(),
            "minor".into(),
            String::new(),
            "apps/cli".into(),
        )
        .with_compare_url("https://github.com/org/repo", |_| false);
        assert_eq!(r.previous_tag, None);
        assert_eq!(r.compare_url, None);
    }

    #[test]
    fn manifest_serialization_roundtrip() {
        let mut m = ReleaseManifest::new("main".into(), "github-actions".into());
        m.add_release(ProjectRelease::new(
            "my-crate".into(),
            "cargo".into(),
            "1.0.0".into(),
            "1.1.0".into(),
            "minor".into(),
            "## Changes\n- Added feature".into(),
            String::new(),
        ));
        let json = m.to_json().expect("serialize");
        let m2 = ReleaseManifest::from_json(&json).expect("deserialize");
        assert_eq!(m2.schema_version, "3.0");
        assert_eq!(m2.releases.len(), 1);
        assert_eq!(m2.releases[0].name, "my-crate");
        assert_eq!(m2.releases[0].ecosystem.as_str(), "cargo");
    }

    #[test]
    fn detect_prerelease_recognises_common_markers() {
        assert!(detect_prerelease("1.0.0-alpha"));
        assert!(detect_prerelease("2.3.4-beta.1"));
        assert!(detect_prerelease("0.5.0-rc.2"));
        assert!(!detect_prerelease("1.0.0"));
        assert!(!detect_prerelease("2.0.0+build.123"));
    }
}
